[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: ~/printer_data/comms/klippy.sock

[file_manager]
queue_gcode_uploads: False
enable_object_processing: True

[data_store]
temperature_store_size: 600
gcode_store_size: 1000

[machine]
provider: systemd_dbus

[authorization]
force_logins: False
cors_domains:
  http://192.168.1.174:7979
  https://printer.skylarenns.com
  http://192.168.1.241
  http://192.168.1.241:4408
  *.local
  *.lan

trusted_clients:
  192.168.1.0/24
  127.0.0.0/8
  ::1/128

[octoprint_compat]

[history]

[update_manager]
enable_auto_refresh: False

[update_manager client fluidd]
type: web
repo: fluidd-core/fluidd
path: ~/fluidd
